### PR TITLE
Password hashing 

### PR DESCRIPTION
**Pull request by OlafDs**
Something goes wrong with the hashing 😕😡

I don't know the problem. Does it need to be in the async function❓

413a3635d8ed9bd42ae8c19616fbdd6e

### CODE REVIEW

**Comment by EyobDejene** [comment]
Maybe something  goes wrong in your if statement 

bcrypt.hash(req.body.password, 10, function (err, hash){
if (err){
	return res.status(400).send(‘Oops! Something went wrong’);
}


You are now using :

if(!error)  -> this means if there is not  a error  run this line :
	return res.status(400).send(‘Oops! Something went wrong’);


i think you don’t want this.
So try to remove the “!” mark form your if statement.

Let me know if this solved the problem

**Comment by OlafDs** [comment]
I fixed it! The code would not work in the registration.js file, but in the users.model.js file in the map models it works! 😃😃

So when you register your password is now being hashed

**Comment by OlafDs** [comment]
@CountNick Oops i forgot to push my changes 😅 😅 😅 I will do it right now

**Comment by CountNick** [comment]
@OlafDs Haha okay!🙈

**Comment by OlafDs** [comment]
@CountNick I pushed my changes now. Can you check if it works now?

**Pull request merged**
